"""Microcredentials Hub — Browse and get AI-recommended industry-relevant micro-courses."""

from fastapi import APIRouter
from pydantic import BaseModel

from app.services.rag_engine import ask_tibu

router = APIRouter()

# ---------------------------------------------------------------------------
# Catalog data — industry-relevant microcredential courses
# ---------------------------------------------------------------------------

CATALOG = [
    # ── Technology ──────────────────────────────────────────────────────────
    {
        "id": "mc-001",
        "title": "Python for Everybody",
        "provider": "University of Michigan",
        "platform": "Coursera",
        "field": "Technology",
        "level": "Beginner",
        "duration": "8 weeks",
        "skills": ["Python", "Data Structures", "Web Scraping", "Databases"],
        "description": "Master Python programming from the ground up. Covers variables, functions, data structures, and working with data — ideal for CS and Engineering students.",
        "certificate": True,
    },
    {
        "id": "mc-002",
        "title": "Google Data Analytics Certificate",
        "provider": "Google",
        "platform": "Coursera",
        "field": "Technology",
        "level": "Beginner",
        "duration": "6 months",
        "skills": ["SQL", "Tableau", "Spreadsheets", "Data Cleaning", "R"],
        "description": "Learn data analysis end-to-end: ask the right questions, clean data, analyze it, and communicate findings. Highly valued by Kenyan employers.",
        "certificate": True,
    },
    {
        "id": "mc-003",
        "title": "IBM Cybersecurity Analyst",
        "provider": "IBM",
        "platform": "Coursera",
        "field": "Technology",
        "level": "Intermediate",
        "duration": "8 months",
        "skills": ["Network Security", "Threat Intelligence", "SIEM", "Incident Response"],
        "description": "Become job-ready in cybersecurity. Covers threat analysis, vulnerability assessment, and security operations — one of the fastest-growing fields in Africa.",
        "certificate": True,
    },
    {
        "id": "mc-004",
        "title": "AWS Cloud Practitioner Essentials",
        "provider": "Amazon Web Services",
        "platform": "AWS Training",
        "field": "Technology",
        "level": "Beginner",
        "duration": "6 hours",
        "skills": ["Cloud Computing", "AWS Services", "Security", "Pricing"],
        "description": "Foundational cloud literacy certification from AWS. Prepares you for the AWS Certified Cloud Practitioner exam — a globally recognised credential.",
        "certificate": True,
    },
    {
        "id": "mc-005",
        "title": "Deep Learning Specialization",
        "provider": "DeepLearning.AI",
        "platform": "Coursera",
        "field": "Technology",
        "level": "Advanced",
        "duration": "5 months",
        "skills": ["Neural Networks", "TensorFlow", "Computer Vision", "NLP"],
        "description": "Build and train deep neural networks taught by Andrew Ng. Essential for students pursuing AI, Machine Learning, or Data Science careers.",
        "certificate": True,
    },
    {
        "id": "mc-006",
        "title": "Microsoft Azure Fundamentals (AZ-900)",
        "provider": "Microsoft",
        "platform": "Microsoft Learn",
        "field": "Technology",
        "level": "Beginner",
        "duration": "10 hours",
        "skills": ["Azure", "Cloud Services", "Networking", "Storage"],
        "description": "Free Microsoft certification prep covering core Azure cloud concepts. Perfect complement to USIU's Computer Science or IT programmes.",
        "certificate": True,
    },
    {
        "id": "mc-007",
        "title": "Full-Stack Web Development Bootcamp",
        "provider": "The App Brewery",
        "platform": "Udemy",
        "field": "Technology",
        "level": "Intermediate",
        "duration": "12 weeks",
        "skills": ["HTML", "CSS", "JavaScript", "React", "Node.js", "MongoDB"],
        "description": "Build real web applications from scratch. Covers the complete modern web stack — ideal for students wanting to build freelance or startup projects.",
        "certificate": True,
    },
    # ── Business & Finance ───────────────────────────────────────────────────
    {
        "id": "mc-008",
        "title": "Google Digital Marketing & E-commerce Certificate",
        "provider": "Google",
        "platform": "Coursera",
        "field": "Business",
        "level": "Beginner",
        "duration": "6 months",
        "skills": ["SEO", "SEM", "Email Marketing", "Social Media", "Analytics"],
        "description": "Learn digital marketing and e-commerce from Google. Covers how to attract customers online, run campaigns, and measure results — directly applicable to Kenyan SMEs.",
        "certificate": True,
    },
    {
        "id": "mc-009",
        "title": "Financial Markets",
        "provider": "Yale University",
        "platform": "Coursera",
        "field": "Business",
        "level": "Beginner",
        "duration": "7 weeks",
        "skills": ["Investments", "Risk Management", "Derivatives", "Behavioral Finance"],
        "description": "Robert Shiller's famous Yale course on financial markets, risk, and behavioural finance. Perfect for Finance and Economics students.",
        "certificate": True,
    },
    {
        "id": "mc-010",
        "title": "Project Management Professional (PMP) Prep",
        "provider": "PMI",
        "platform": "edX",
        "field": "Business",
        "level": "Intermediate",
        "duration": "3 months",
        "skills": ["Agile", "Scrum", "Risk Management", "Budgeting", "Stakeholder Management"],
        "description": "Prepare for one of the most valued management certifications globally. Recognised by every major employer in Kenya and internationally.",
        "certificate": True,
    },
    {
        "id": "mc-011",
        "title": "Entrepreneurship Specialization",
        "provider": "Wharton School",
        "platform": "Coursera",
        "field": "Business",
        "level": "Intermediate",
        "duration": "4 months",
        "skills": ["Business Model", "Fundraising", "Growth Strategy", "Launch Planning"],
        "description": "Learn to develop, pitch, and launch a new venture from Wharton. Covers ideation to funding — ideal for aspiring USIU entrepreneurs.",
        "certificate": True,
    },
    {
        "id": "mc-012",
        "title": "Excel Skills for Business",
        "provider": "Macquarie University",
        "platform": "Coursera",
        "field": "Business",
        "level": "Beginner",
        "duration": "4 months",
        "skills": ["Excel", "Data Analysis", "Dashboards", "Financial Modelling"],
        "description": "Master Excel from basics to advanced analytics and automation. One of the most universally requested skills by Kenyan recruiters across all industries.",
        "certificate": True,
    },
    # ── Media & Communication ────────────────────────────────────────────────
    {
        "id": "mc-013",
        "title": "Graphic Design Specialization",
        "provider": "California Institute of the Arts",
        "platform": "Coursera",
        "field": "Creative",
        "level": "Beginner",
        "duration": "6 months",
        "skills": ["Typography", "Composition", "Branding", "Adobe Illustrator", "InDesign"],
        "description": "Build professional design skills from the ground up. Covers visual principles and industry-standard tools used in marketing, publishing, and media.",
        "certificate": True,
    },
    {
        "id": "mc-014",
        "title": "Introduction to UI/UX Design",
        "provider": "Google",
        "platform": "Coursera",
        "field": "Creative",
        "level": "Beginner",
        "duration": "7 months",
        "skills": ["Figma", "User Research", "Wireframing", "Prototyping", "Usability Testing"],
        "description": "Google's UX Design Certificate — learn to design apps and websites that people love to use. One of the most in-demand skills in Kenya's growing tech sector.",
        "certificate": True,
    },
    {
        "id": "mc-015",
        "title": "Social Media Marketing Masterclass",
        "provider": "Meta",
        "platform": "Coursera",
        "field": "Creative",
        "level": "Beginner",
        "duration": "7 months",
        "skills": ["Facebook Ads", "Instagram", "Content Strategy", "Analytics", "Campaign Management"],
        "description": "Meta's official marketing certificate. Learn to create and run effective paid campaigns on the world's largest social platforms.",
        "certificate": True,
    },
    # ── Health & Life Sciences ───────────────────────────────────────────────
    {
        "id": "mc-016",
        "title": "Health Informatics Specialization",
        "provider": "Johns Hopkins University",
        "platform": "Coursera",
        "field": "Health",
        "level": "Intermediate",
        "duration": "5 months",
        "skills": ["EHR Systems", "Health Data", "Clinical Workflows", "Public Health IT"],
        "description": "Bridge healthcare and technology. Covers digital health records, health data analysis, and informatics tools — high demand in Kenya's evolving health sector.",
        "certificate": True,
    },
    {
        "id": "mc-017",
        "title": "Mental Health and Wellbeing",
        "provider": "University of Melbourne",
        "platform": "Coursera",
        "field": "Health",
        "level": "Beginner",
        "duration": "4 weeks",
        "skills": ["Psychological First Aid", "Stress Management", "Resilience", "Mindfulness"],
        "description": "Evidence-based strategies for understanding and improving mental wellbeing. Relevant to all students and future professionals who work with people.",
        "certificate": True,
    },
    # ── Law & Governance ─────────────────────────────────────────────────────
    {
        "id": "mc-018",
        "title": "Introduction to International Law",
        "provider": "University of Amsterdam",
        "platform": "Coursera",
        "field": "Law",
        "level": "Beginner",
        "duration": "6 weeks",
        "skills": ["International Treaties", "Human Rights Law", "UN System", "Dispute Resolution"],
        "description": "Explore international law, human rights, and global governance. Valuable for Law, IR, and Political Science students aiming for NGO or diplomatic careers.",
        "certificate": True,
    },
    {
        "id": "mc-019",
        "title": "Data Privacy Fundamentals",
        "provider": "IBM",
        "platform": "edX",
        "field": "Law",
        "level": "Beginner",
        "duration": "3 weeks",
        "skills": ["GDPR", "Data Ethics", "Privacy by Design", "Compliance"],
        "description": "Understand data privacy regulations and ethical data handling. Essential for any student entering tech, business, or public policy in the digital age.",
        "certificate": True,
    },
    # ── Sustainability & Environment ─────────────────────────────────────────
    {
        "id": "mc-020",
        "title": "Sustainability and Development",
        "provider": "University of Michigan",
        "platform": "Coursera",
        "field": "Environment",
        "level": "Beginner",
        "duration": "10 weeks",
        "skills": ["SDGs", "Environmental Policy", "Green Economy", "Climate Change"],
        "description": "Understand the relationship between human development and environmental sustainability. Directly aligned with Kenya's Vision 2030 and the SDGs.",
        "certificate": True,
    },
    # ── Technology (extended) ────────────────────────────────────────────────
    {
        "id": "mc-021",
        "title": "CS50: Introduction to Computer Science",
        "provider": "Harvard University",
        "platform": "edX",
        "field": "Technology",
        "level": "Beginner",
        "duration": "12 weeks",
        "skills": ["C", "Python", "SQL", "Algorithms", "Data Structures"],
        "description": "Harvard's legendary intro to computer science. Builds strong programming foundations from first principles — a favourite starting point worldwide.",
        "certificate": True,
    },
    {
        "id": "mc-022",
        "title": "Google IT Support Professional Certificate",
        "provider": "Google",
        "platform": "Coursera",
        "field": "Technology",
        "level": "Beginner",
        "duration": "6 months",
        "skills": ["Troubleshooting", "Networking", "Operating Systems", "System Administration"],
        "description": "Job-ready IT support skills with no prior experience needed. Opens the door to entry-level IT roles across Kenya's growing tech industry.",
        "certificate": True,
    },
    {
        "id": "mc-023",
        "title": "Google Cybersecurity Professional Certificate",
        "provider": "Google",
        "platform": "Coursera",
        "field": "Technology",
        "level": "Beginner",
        "duration": "6 months",
        "skills": ["SIEM", "Linux", "Python", "Threat Detection", "Risk Management"],
        "description": "Learn to protect organisations from cyber threats. Covers security tools, Linux, Python and incident response — a fast-track into one of Africa's most in-demand fields.",
        "certificate": True,
    },
    {
        "id": "mc-024",
        "title": "Meta Front-End Developer Certificate",
        "provider": "Meta",
        "platform": "Coursera",
        "field": "Technology",
        "level": "Beginner",
        "duration": "7 months",
        "skills": ["HTML", "CSS", "JavaScript", "React", "Version Control"],
        "description": "Build responsive websites and apps with React. Meta's official developer credential, ideal for students targeting front-end or full-stack roles.",
        "certificate": True,
    },
    {
        "id": "mc-025",
        "title": "IBM Data Science Professional Certificate",
        "provider": "IBM",
        "platform": "Coursera",
        "field": "Data & AI",
        "level": "Intermediate",
        "duration": "5 months",
        "skills": ["Python", "SQL", "Machine Learning", "Data Visualization", "Jupyter"],
        "description": "Hands-on data science from Python basics to machine learning models. Includes real projects that build a job-ready portfolio.",
        "certificate": True,
    },
    {
        "id": "mc-026",
        "title": "Machine Learning Specialization",
        "provider": "Stanford & DeepLearning.AI",
        "platform": "Coursera",
        "field": "Data & AI",
        "level": "Intermediate",
        "duration": "3 months",
        "skills": ["Supervised Learning", "Neural Networks", "Recommender Systems", "TensorFlow"],
        "description": "Andrew Ng's updated flagship ML course. The definitive starting point for a machine learning or AI career.",
        "certificate": True,
    },
    {
        "id": "mc-027",
        "title": "AI For Everyone",
        "provider": "DeepLearning.AI",
        "platform": "Coursera",
        "field": "Data & AI",
        "level": "Beginner",
        "duration": "4 weeks",
        "skills": ["AI Strategy", "Machine Learning Concepts", "AI Ethics", "Workflow"],
        "description": "A non-technical guide to what AI can and cannot do, and how to apply it in any organisation. Perfect for business, media and law students.",
        "certificate": True,
    },
    {
        "id": "mc-028",
        "title": "Generative AI with Large Language Models",
        "provider": "AWS & DeepLearning.AI",
        "platform": "Coursera",
        "field": "Data & AI",
        "level": "Advanced",
        "duration": "3 weeks",
        "skills": ["LLMs", "Prompt Engineering", "Fine-Tuning", "Transformers"],
        "description": "Understand how generative AI and LLMs work and how to build with them. One of the most future-relevant skills available today.",
        "certificate": True,
    },
    {
        "id": "mc-029",
        "title": "Prompt Engineering for Developers",
        "provider": "DeepLearning.AI & OpenAI",
        "platform": "DeepLearning.AI",
        "field": "Data & AI",
        "level": "Beginner",
        "duration": "3 hours",
        "skills": ["Prompt Design", "LLM APIs", "Chatbots", "Summarisation"],
        "description": "Learn to build applications with large language models through effective prompting. Short, practical, and immediately useful.",
        "certificate": False,
    },
    {
        "id": "mc-030",
        "title": "Microsoft Power BI Data Analyst (PL-300)",
        "provider": "Microsoft",
        "platform": "Microsoft Learn",
        "field": "Data & AI",
        "level": "Intermediate",
        "duration": "2 months",
        "skills": ["Power BI", "DAX", "Data Modelling", "Dashboards"],
        "description": "Prepare for Microsoft's PL-300 certification and learn to turn data into interactive dashboards — a highly requested business analytics skill.",
        "certificate": True,
    },
    {
        "id": "mc-031",
        "title": "Cisco Networking Basics (CCNA Prep)",
        "provider": "Cisco",
        "platform": "Cisco Networking Academy",
        "field": "Technology",
        "level": "Beginner",
        "duration": "8 weeks",
        "skills": ["Networking", "IP Addressing", "Routing", "Switching"],
        "description": "Foundational networking knowledge that leads toward the globally recognised CCNA. Strong for IT, telecoms and infrastructure careers.",
        "certificate": True,
    },
    {
        "id": "mc-032",
        "title": "Docker & Kubernetes: The Complete Guide",
        "provider": "Stephen Grider",
        "platform": "Udemy",
        "field": "Technology",
        "level": "Intermediate",
        "duration": "22 hours",
        "skills": ["Docker", "Kubernetes", "CI/CD", "Containers"],
        "description": "Master containers and orchestration used by modern engineering teams. Essential DevOps skills for deploying real-world applications.",
        "certificate": True,
    },
    {
        "id": "mc-033",
        "title": "Flutter & Dart — Mobile App Development",
        "provider": "London App Brewery",
        "platform": "Udemy",
        "field": "Technology",
        "level": "Intermediate",
        "duration": "28 hours",
        "skills": ["Flutter", "Dart", "Mobile UI", "Firebase"],
        "description": "Build iOS and Android apps from a single codebase. Great for students who want to ship mobile products or freelance.",
        "certificate": True,
    },
    {
        "id": "mc-034",
        "title": "Meta Android Developer Certificate",
        "provider": "Meta",
        "platform": "Coursera",
        "field": "Technology",
        "level": "Intermediate",
        "duration": "8 months",
        "skills": ["Kotlin", "Android Studio", "Jetpack Compose", "APIs"],
        "description": "Learn to build native Android apps with Kotlin. Mobile-first skills that match Kenya's booming app economy.",
        "certificate": True,
    },
    {
        "id": "mc-035",
        "title": "SQL for Data Science",
        "provider": "University of California, Davis",
        "platform": "Coursera",
        "field": "Data & AI",
        "level": "Beginner",
        "duration": "4 weeks",
        "skills": ["SQL", "Queries", "Data Wrangling", "Databases"],
        "description": "Learn to query and analyse data with SQL — the single most requested data skill across every industry.",
        "certificate": True,
    },
    {
        "id": "mc-036",
        "title": "CompTIA Security+ Certification Prep",
        "provider": "CompTIA",
        "platform": "Udemy",
        "field": "Technology",
        "level": "Intermediate",
        "duration": "20 hours",
        "skills": ["Network Security", "Cryptography", "Risk Management", "Compliance"],
        "description": "Prepare for the industry-standard entry-level cybersecurity certification recognised by employers and government agencies worldwide.",
        "certificate": True,
    },
    # ── Business & Finance (extended) ────────────────────────────────────────
    {
        "id": "mc-037",
        "title": "Google Project Management Certificate",
        "provider": "Google",
        "platform": "Coursera",
        "field": "Business",
        "level": "Beginner",
        "duration": "6 months",
        "skills": ["Agile", "Scrum", "Planning", "Risk", "Stakeholder Management"],
        "description": "Start a career in project management with no experience required. Covers Agile and traditional methods valued across every sector.",
        "certificate": True,
    },
    {
        "id": "mc-038",
        "title": "CFA Level I — Foundations",
        "provider": "CFA Institute",
        "platform": "edX",
        "field": "Business",
        "level": "Advanced",
        "duration": "6 months",
        "skills": ["Ethics", "Equity", "Fixed Income", "Portfolio Management"],
        "description": "Begin the world's most respected investment credential. Ideal for Finance students targeting asset management, banking or research.",
        "certificate": True,
    },
    {
        "id": "mc-039",
        "title": "Supply Chain Management Specialization",
        "provider": "Rutgers University",
        "platform": "Coursera",
        "field": "Business",
        "level": "Intermediate",
        "duration": "4 months",
        "skills": ["Logistics", "Operations", "Procurement", "Forecasting"],
        "description": "Understand how goods move from supplier to customer. A high-value skill for Kenya's logistics, manufacturing and retail sectors.",
        "certificate": True,
    },
    {
        "id": "mc-040",
        "title": "Business Analytics Specialization",
        "provider": "Wharton School",
        "platform": "Coursera",
        "field": "Business",
        "level": "Intermediate",
        "duration": "5 months",
        "skills": ["Customer Analytics", "Operations Analytics", "People Analytics", "Accounting Analytics"],
        "description": "Learn to make data-driven business decisions from Wharton faculty. Bridges business strategy with analytics.",
        "certificate": True,
    },
    {
        "id": "mc-041",
        "title": "Successful Negotiation: Strategies & Skills",
        "provider": "University of Michigan",
        "platform": "Coursera",
        "field": "Business",
        "level": "Beginner",
        "duration": "4 weeks",
        "skills": ["Negotiation", "Persuasion", "Deal-Making", "Conflict Resolution"],
        "description": "Master a skill you'll use for life — negotiating salaries, deals and partnerships. Practical and immediately applicable.",
        "certificate": True,
    },
    {
        "id": "mc-042",
        "title": "Fundamentals of Accounting",
        "provider": "University of Illinois",
        "platform": "Coursera",
        "field": "Business",
        "level": "Beginner",
        "duration": "3 months",
        "skills": ["Financial Statements", "Bookkeeping", "Managerial Accounting", "Analysis"],
        "description": "Build a solid accounting foundation that supports ACCA, CPA and finance careers. Clear, structured, and widely applicable.",
        "certificate": True,
    },
    # ── Creative & Media (extended) ──────────────────────────────────────────
    {
        "id": "mc-043",
        "title": "Adobe Photoshop — Complete Mastery",
        "provider": "Adobe / Phlearn",
        "platform": "Udemy",
        "field": "Creative",
        "level": "Beginner",
        "duration": "15 hours",
        "skills": ["Photo Editing", "Retouching", "Compositing", "Layers"],
        "description": "Learn the world's leading image-editing tool from scratch to professional. Core skill for design, media and marketing students.",
        "certificate": True,
    },
    {
        "id": "mc-044",
        "title": "Video Production & Editing",
        "provider": "Michigan State University",
        "platform": "Coursera",
        "field": "Creative",
        "level": "Beginner",
        "duration": "6 weeks",
        "skills": ["Filming", "Editing", "Storytelling", "Premiere Pro"],
        "description": "Produce professional-quality video content from planning to final cut. Perfect for Journalism, Film and Communication students.",
        "certificate": True,
    },
    {
        "id": "mc-045",
        "title": "The Strategy of Content Marketing",
        "provider": "University of California, Davis",
        "platform": "Coursera",
        "field": "Creative",
        "level": "Beginner",
        "duration": "4 weeks",
        "skills": ["Copywriting", "Content Strategy", "SEO Writing", "Storytelling"],
        "description": "Learn to plan and write content that attracts and converts audiences. A versatile skill for media, marketing and entrepreneurship.",
        "certificate": True,
    },
    {
        "id": "mc-046",
        "title": "3D Modelling & Animation with Blender",
        "provider": "GameDev.tv",
        "platform": "Udemy",
        "field": "Creative",
        "level": "Intermediate",
        "duration": "30 hours",
        "skills": ["Blender", "3D Modelling", "Texturing", "Animation"],
        "description": "Create 3D models and animations with the free, industry-used Blender. Great for design, gaming and visual effects interests.",
        "certificate": True,
    },
    # ── Communication & Personal Development ─────────────────────────────────
    {
        "id": "mc-047",
        "title": "Learning How to Learn",
        "provider": "McMaster University & UC San Diego",
        "platform": "Coursera",
        "field": "Communication",
        "level": "Beginner",
        "duration": "4 weeks",
        "skills": ["Study Techniques", "Memory", "Focus", "Productivity"],
        "description": "The world's most popular online course — powerful techniques to learn anything faster and beat procrastination. Useful for every student.",
        "certificate": True,
    },
    {
        "id": "mc-048",
        "title": "Introduction to Public Speaking",
        "provider": "University of Washington",
        "platform": "edX",
        "field": "Communication",
        "level": "Beginner",
        "duration": "10 weeks",
        "skills": ["Public Speaking", "Persuasion", "Presentation", "Confidence"],
        "description": "Become a confident, compelling speaker. Essential for pitches, presentations, interviews and leadership.",
        "certificate": True,
    },
    {
        "id": "mc-049",
        "title": "Emotional & Social Intelligence",
        "provider": "University of California, Davis",
        "platform": "Coursera",
        "field": "Communication",
        "level": "Beginner",
        "duration": "3 weeks",
        "skills": ["Emotional Intelligence", "Empathy", "Teamwork", "Self-Awareness"],
        "description": "Develop the people skills employers value most. Improves collaboration, leadership and workplace relationships.",
        "certificate": True,
    },
    {
        "id": "mc-050",
        "title": "English for Career Development",
        "provider": "University of Pennsylvania",
        "platform": "Coursera",
        "field": "Communication",
        "level": "Beginner",
        "duration": "5 weeks",
        "skills": ["Business English", "CV Writing", "Interviews", "Networking"],
        "description": "Sharpen professional English for job searches, CVs and interviews. A practical boost for entering the global job market.",
        "certificate": True,
    },
    # ── Health & Life Sciences (extended) ────────────────────────────────────
    {
        "id": "mc-051",
        "title": "Introduction to Food and Health",
        "provider": "Stanford University",
        "platform": "Coursera",
        "field": "Health",
        "level": "Beginner",
        "duration": "5 weeks",
        "skills": ["Nutrition", "Public Health", "Wellness", "Diet"],
        "description": "Understand the link between food, health and lifestyle. Valuable for health science, nursing and wellness-focused students.",
        "certificate": True,
    },
    {
        "id": "mc-052",
        "title": "Epidemiology: The Basic Science of Public Health",
        "provider": "University of North Carolina",
        "platform": "Coursera",
        "field": "Health",
        "level": "Beginner",
        "duration": "6 weeks",
        "skills": ["Epidemiology", "Disease Surveillance", "Study Design", "Public Health"],
        "description": "Learn how public health investigates disease and protects populations — highly relevant after recent global health events.",
        "certificate": True,
    },
    # ── Law & Governance (extended) ──────────────────────────────────────────
    {
        "id": "mc-053",
        "title": "Contract Law: From Trust to Promise to Contract",
        "provider": "Harvard University",
        "platform": "edX",
        "field": "Law",
        "level": "Intermediate",
        "duration": "8 weeks",
        "skills": ["Contract Law", "Legal Reasoning", "Agreements", "Liability"],
        "description": "Explore the foundations of contract law with a Harvard professor. Strong grounding for Law and business-minded students.",
        "certificate": True,
    },
    {
        "id": "mc-054",
        "title": "Intellectual Property Law",
        "provider": "University of Pennsylvania",
        "platform": "Coursera",
        "field": "Law",
        "level": "Beginner",
        "duration": "4 weeks",
        "skills": ["Copyright", "Patents", "Trademarks", "IP Strategy"],
        "description": "Understand how ideas, brands and inventions are protected. Increasingly vital for creators, founders and tech professionals.",
        "certificate": True,
    },
    # ── Environment & Sustainability (extended) ──────────────────────────────
    {
        "id": "mc-055",
        "title": "Renewable Energy & Green Building",
        "provider": "Technical University of Denmark",
        "platform": "Coursera",
        "field": "Environment",
        "level": "Intermediate",
        "duration": "6 weeks",
        "skills": ["Solar Energy", "Wind Power", "Energy Efficiency", "Sustainable Design"],
        "description": "Learn how clean energy systems work and how they're deployed. Aligned with Kenya's leadership in geothermal and solar energy.",
        "certificate": True,
    },
    {
        "id": "mc-056",
        "title": "Climate Change: Solutions",
        "provider": "University of Exeter",
        "platform": "FutureLearn",
        "field": "Environment",
        "level": "Beginner",
        "duration": "5 weeks",
        "skills": ["Climate Science", "Mitigation", "Adaptation", "Policy"],
        "description": "Explore practical solutions to the climate crisis across technology, policy and behaviour. Great for changemakers and future leaders.",
        "certificate": True,
    },
]

FIELDS = sorted(set(c["field"] for c in CATALOG))
LEVELS = ["Beginner", "Intermediate", "Advanced"]


# ---------------------------------------------------------------------------
# Models
# ---------------------------------------------------------------------------


class RecommendRequest(BaseModel):
    major: str
    interests: list[str] = []
    career_goal: str = ""


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------


@router.get("/catalog")
async def get_catalog(field: str = "", level: str = "", search: str = ""):
    """Return the full microcredential catalog, optionally filtered."""
    results = CATALOG
    if field:
        results = [c for c in results if c["field"].lower() == field.lower()]
    if level:
        results = [c for c in results if c["level"].lower() == level.lower()]
    if search:
        q = search.lower()
        results = [
            c for c in results
            if q in c["title"].lower() or q in c["description"].lower()
            or any(q in s.lower() for s in c["skills"])
        ]
    return {"courses": results, "total": len(results), "fields": FIELDS, "levels": LEVELS}


@router.post("/recommend")
async def recommend_microcredentials(request: RecommendRequest):
    """AI-powered microcredential recommendations based on a student's academic profile."""
    catalog_summary = "\n".join(
        f"- [{c['id']}] {c['title']} ({c['platform']}, {c['level']}, {c['field']}): {', '.join(c['skills'])}"
        for c in CATALOG
    )

    question = (
        f"I am a {request.major} major at USIU-Africa. "
        + (f"My career goal is: {request.career_goal}. " if request.career_goal else "")
        + (f"My interests include: {', '.join(request.interests)}. " if request.interests else "")
        + f"\n\nHere is our microcredential catalog:\n{catalog_summary}\n\n"
        "Based on my degree and goals, recommend the 4 most relevant microcredential courses from the catalog above. "
        "For each recommendation, cite the course title, explain in 2 sentences why it fits my profile, "
        "and describe how it complements my degree at USIU-Africa. Format your response as a numbered list."
    )

    result = await ask_tibu(question)
    return result


@router.get("/fields")
async def get_fields():
    """Return available subject fields for filtering."""
    return {"fields": FIELDS, "levels": LEVELS}
